### ISSUE TITLE
Article view page

### ISSUE THREAD

**Issue by falansari** [falansari/open_blog_site#10]
- [x] automatically generate new view page for each article stored in database

- [x] show full view of article (title, description, attachments)

- [x] show article writer's name

- [ ] show article writer's avatar #32 

- [ ] view article's comments (paginated) #12 

- [ ] display article's attachments (downloadable) #31
